#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER fb_owner WITH LOGIN PASSWORD '$POSTGRES_FB_OWNER_PASSWORD' NOSUPERUSER NOCREATEDB;
    CREATE USER fb_ddl_flyway WITH LOGIN PASSWORD '$POSTGRES_FB_DDL_FLYWAY_PASSWORD' NOSUPERUSER NOCREATEDB;
    CREATE USER fb_dml_api WITH LOGIN PASSWORD '$POSTGRES_FB_DML_API_PASSWORD' NOSUPERUSER NOCREATEDB;
    
    CREATE DATABASE fb OWNER fb_owner;
    GRANT ALL PRIVILEGES ON DATABASE fb TO fb_owner;
    GRANT ALL PRIVILEGES ON DATABASE fb TO fb_ddl_flyway;
    GRANT CONNECT ON DATABASE fb TO fb_dml_api;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "fb" <<-EOSQL
    GRANT ALL ON SCHEMA public TO fb_owner;
    GRANT USAGE, CREATE ON SCHEMA public TO fb_ddl_flyway;
    GRANT USAGE ON SCHEMA public TO fb_dml_api;
    
    ALTER DEFAULT PRIVILEGES FOR ROLE fb_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fb_dml_api;
    ALTER DEFAULT PRIVILEGES FOR ROLE fb_ddl_flyway IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fb_dml_api;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER kc_owner WITH LOGIN PASSWORD '$POSTGRES_KC_OWNER_PASSWORD' NOSUPERUSER NOCREATEDB;
    
    CREATE DATABASE kc OWNER kc_owner;
    GRANT ALL PRIVILEGES ON DATABASE kc TO kc_owner;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "kc" <<-EOSQL
    GRANT ALL ON SCHEMA public TO kc_owner;
    
    ALTER DEFAULT PRIVILEGES FOR ROLE kc_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kc_owner;
EOSQL